spring.application.name=ms-rutaexpress-bff
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/7ecd33b8-57e2-4e0b-ace8-8c8fd532708f/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/7ecd33b8-57e2-4e0b-ace8-8c8fd532708f/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.audiences=api://8e9ad887-fcb6-4d33-9544-0657e51590e3
# Habilita el detalle del rechazo de Spring Security en la consola
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
